
server:
  port: 9100
logging.level.org.springframework: DEBUG

security:
  jwt:
    key:
      public: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCqWWitxbuvFLWI7EcBHJm9z9OjM+O/OvcNrJazCHf9eRHeTmdpu1CcggdGBXMBOowWOCJlgB6A7fPlz77AeDsLnf1WFzaf58pligJqs34VVrbnum9u5yMynjXnwlvdUXDOobRKab/loxjFLJelLV5IVscu3eKttXDYblUpmA4+oQIDAQAB
      private: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAKpZaK3Fu68UtYjsRwEcmb3P06Mz47869w2slrMId/15Ed5OZ2m7UJyCB0YFcwE6jBY4ImWAHoDt8+XPvsB4Owud/VYXNp/nymWKAmqzfhVWtue6b27nIzKeNefCW91RcM6htEppv+WjGMUsl6UtXkhWxy7d4q21cNhuVSmYDj6hAgMBAAECgYBeSfzh6oe3IhxVPIsUt3L1mDpJpGgUKhwjKnuDf1WDLGdSiE0/Pdohtus1u8BrVq/BgLKxQdggfxU4B+RKfoIXRTmPn6XWE3GPQRJKtn8DQdKY+dn5itmMp4je+Y3+89pG9H2/YkGIOUE1QqtAdHANaY1uBPneoifQt1WMeUyKTQJBAOEJ6hUUKUx6HuWeYg8pxZlLir2n7u8v6xPGWyrxZH29LR39d0aPjQ0oJgzk3TzwLpKz9pDX3HIuTHdWUMTbxicCQQDByUcBhkLasJhC5EO/WnIot9YkbVAoQZb0cgBiDn3sXz4EQ2B6pG0ziACBzAJ3fLs1kfL5pejFJQNkjoMEfdn3AkEAivGkJf+cwCtmiD+SK+qOpmeN8iuNywC7FCqUf58rfLcg9DNbQaXAYS84zx0/vDBPkSSsSCH/akBL1iLlG6bWYQJAWUfUcP1ce8j0vYzRMa4H/n6EKJA8Z++gDssfJg4rMeXHestX/ekXbrBwG1zUnhxXXBz75szrazjcUU3fSwh4jQJAGFIK5tM0t+1Yt0536lGsoSIvWvDogzkIMuaNfRVyvxmk5rQGxFJsNw1aWGBWUgLTppaNLIHQFIcqJIVmqWAd9A==

spring.datasource.url: jdbc:mysql://localhost:3306/cow
spring.datasource.username: root
spring.datasource.password: cow2019

# Mailing
mail.protocol: smtp
mail.smtp.host: smtp.capitanoferta.com
mail.smtp.port: 587
mail.support.username: no-reply@capitanoferta.com
mail.support.password: coweb2018
mail.default.encoding: UTF-8
